In [2]:
import numpy as np

In [4]:
a1 = np.array([1,2,3,5,6])

In [5]:
a1

array([1, 2, 3, 5, 6])

In [6]:
a1*3

array([ 3,  6,  9, 15, 18])

In [7]:
a1.dtype

dtype('int32')

In [9]:
a2=np.array([1.2,3.2,4.2],dtype=int)

In [15]:
a3=np.array([[1,2,3],[3,4],[5,6]])

In [16]:
a3

array([list([1, 2, 3]), list([3, 4]), list([5, 6])], dtype=object)

In [18]:
a3.shape

(3,)

In [19]:
a3.dtype

dtype('O')

In [20]:
b = np.array([[1,2,3],[3,5,6],[5,6,6]])

In [21]:
b

array([[1, 2, 3],
       [3, 5, 6],
       [5, 6, 6]])

In [22]:
b.shape

(3, 3)

In [23]:
b.tolist

<function ndarray.tolist>

In [24]:
b.tolist()

[[1, 2, 3], [3, 5, 6], [5, 6, 6]]

In [25]:
c=np.array([1,2,3,4,5])

In [26]:
c

array([1, 2, 3, 4, 5])

In [27]:
c.shape

(5,)

In [31]:
d=np.array([[[1,2,3],[2,3,4]],[[1,2,3],[2,3,4]]])

In [32]:
d

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [33]:
d.shape

(2, 2, 3)

In [34]:
#含义：2:2个二维数组，2:二维数组为2行，3：二维数组为3列（元素个数，元素行数，元素列数）

In [35]:
d.dtype

dtype('int32')

In [37]:
d.tolist()

[[[1, 2, 3], [2, 3, 4]], [[1, 2, 3], [2, 3, 4]]]

In [ ]:
import random

In [51]:
lt = [i for i in range(500)]

In [53]:
s = np.array([[i for i in range(500)],[i**2 for i in range(500)],[i**3 for i in range(500)],[i**4 for i in range(500)],[i**5 for i in range(500)]])

In [54]:
s

array([[             0,              1,              2, ...,
                   497,            498,            499],
       [             0,              1,              4, ...,
                247009,         248004,         249001],
       [             0,              1,              8, ...,
             122763473,      123505992,      124251499],
       [             0,              1,             16, ...,
           61013446081,    61505984016,    62001498001],
       [             0,              1,             32, ...,
        30323682702257, 30629980039968, 30938747502499]], dtype=int64)

In [75]:
import random
random.random()
[random.randint(2,10) for i in range(10)]

[5, 7, 2, 7, 6, 4, 5, 6, 9, 9]

In [70]:
s.shape

(5, 500)

In [72]:
x = np.linspace(5,10,50)

In [73]:
x

array([ 5.        ,  5.10204082,  5.20408163,  5.30612245,  5.40816327,
        5.51020408,  5.6122449 ,  5.71428571,  5.81632653,  5.91836735,
        6.02040816,  6.12244898,  6.2244898 ,  6.32653061,  6.42857143,
        6.53061224,  6.63265306,  6.73469388,  6.83673469,  6.93877551,
        7.04081633,  7.14285714,  7.24489796,  7.34693878,  7.44897959,
        7.55102041,  7.65306122,  7.75510204,  7.85714286,  7.95918367,
        8.06122449,  8.16326531,  8.26530612,  8.36734694,  8.46938776,
        8.57142857,  8.67346939,  8.7755102 ,  8.87755102,  8.97959184,
        9.08163265,  9.18367347,  9.28571429,  9.3877551 ,  9.48979592,
        9.59183673,  9.69387755,  9.79591837,  9.89795918, 10.        ])

In [80]:
e = np.random.randint(1,9,(6,4))

In [81]:
e

array([[7, 8, 6, 8],
       [7, 6, 1, 2],
       [7, 6, 4, 8],
       [6, 5, 3, 2],
       [3, 8, 6, 3],
       [1, 3, 6, 6]])

In [82]:
e+23

array([[30, 31, 29, 31],
       [30, 29, 24, 25],
       [30, 29, 27, 31],
       [29, 28, 26, 25],
       [26, 31, 29, 26],
       [24, 26, 29, 29]])

In [83]:
np.zeros(10) #零数组，用来创建特殊数组或者作为容器装载数据

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
np.empty(10) #空数组，里面是垃圾值，可以作为数据容器

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [89]:
np.empty((5,4))

array([[4.47650503e-312, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000],
       [8.90104238e-307, 5.30276956e+180, 3.31033942e-033,
        6.98206700e-076],
       [3.65804233e-086, 3.35560310e-143, 6.01433264e+175,
        6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 6.05088884e-066,
        1.31267446e-071],
       [2.80054289e-032, 3.79914649e+175, 7.80986608e-144,
        1.50008929e+248]])

In [91]:
np.ones(5) #一数组，数据容器或者参与特殊数组的构造

array([1., 1., 1., 1., 1.])

In [92]:
np.identity(6) #是方阵；只有对角线的元素不为0，其他元素都为0，默认浮点型

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [98]:
np.arange(0,12,2)

array([ 0,  2,  4,  6,  8, 10])

In [101]:
f=np.arange(-1,6,2)

In [102]:
np.zeros_like(f)

array([0, 0, 0, 0])

In [114]:
g=np.arange(1,17).reshape(2,8)  #使用arange函数创建二维数组，行数*列数=arange的元素个数

In [108]:
g

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [111]:
h = np.arange(1,17).reshape(16,1) #reshape函数的反操作 ravel

In [112]:
np.ravel(h)  #将多维数组转换为一维数组

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [115]:
i = np.arange(1,17).reshape(4,4) 

In [116]:
i

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [121]:
np.ones_like(i)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [122]:
j = np.zeros_like(i)

In [123]:
j

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [124]:
np.ravel(j)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [125]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [126]:
kk=np.arange(1,10).reshape(3,3)

In [134]:
kk

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
kk[0,1]

2

In [129]:
np.array([1,3,4,2.5,3.8])

array([1. , 3. , 4. , 2.5, 3.8])

In [131]:
s=np.array([1,3,4,2.5,3.8],dtype=object)

In [132]:
s

array([1, 3, 4, 2.5, 3.8], dtype=object)

In [133]:
s.dtype

dtype('O')

In [137]:
ss = np.identity(4)

In [138]:
ss

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [139]:
ss[1,0]=2

In [140]:
ss

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [141]:
ss[2,1]=2

In [142]:
ss

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 0., 1.]])

In [143]:
ss[3,2]=2

In [144]:
ss

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 2., 1.]])

In [147]:
def func(n,k):
    ar=np.identity(n)
    for i in range(1,n):
        ar[i,i-1]=k
    return ar

In [148]:
res = func(4,2)

In [149]:
res

array([[1., 0., 0., 0.],
       [2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 2., 1.]])

In [152]:
res = func(8,-2)

In [153]:
res

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [-2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0., -2.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0., -2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0., -2.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0., -2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0., -2.,  1.]])

In [154]:
np.ones_like(res)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [156]:
np.zeros_like(res)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [157]:
np.empty_like(res)

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [158]:
%who

a1	 a2	 a3	 b	 c	 d	 e	 f	 func	 
funs	 g	 h	 i	 j	 k	 kk	 ls	 lt	 
np	 random	 res	 s	 ss	 x	 


In [159]:
res.size

64

In [160]:
res.ndim

2

In [3]:
xx = np.array([1,2,3],dtype=float)

In [4]:
xx

array([1., 2., 3.])

In [5]:
xx.astype(object) #修改类型

array([1.0, 2.0, 3.0], dtype=object)

In [6]:
xx.astype(int)

array([1, 2, 3])

In [7]:
x1=np.arange(1,10)

In [8]:
x1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x2=np.random.randint(3,18,9)

In [12]:
x2

array([17,  5,  7,  5, 17, 10,  6,  8, 14])

In [13]:
x1+x2

array([18,  7, 10,  9, 22, 16, 13, 16, 23])

In [14]:
x1*x2

array([ 17,  10,  21,  20,  85,  60,  42,  64, 126])

In [18]:
x3= np.arange(1,10).reshape(3,3)
x4=np.random.randint(3,19,(3,3))

In [19]:
x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
x4

array([[ 5, 11, 10],
       [10,  3, 16],
       [15,  5,  8]])

In [21]:
x3*x4

array([[  5,  22,  30],
       [ 40,  15,  96],
       [105,  40,  72]])

In [22]:
x3**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)