In [2]:
import numpy as np
a1 = np.arange(1,10)
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a2 = np.arange(10,-2,-2)
a2

array([10,  8,  6,  4,  2,  0])

In [7]:
a3 = np.arange(-2,10).reshape(3,4)

In [8]:
a3

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [9]:
a4 =np.random.randint(2,15,(3,4))

In [10]:
a4

array([[ 4, 12, 11,  3],
       [14, 13,  4,  2],
       [ 9,  4, 13,  8]])

In [14]:
f=lambda x,y:(((x**2)-(y**3)+(6*x*(y**2))-12)/(5*y-7*x*y+3)).sum()
a5= np.arange(1,10)
a6=np.arange(1,10)

In [15]:
f(a5,a6)

-43.43806242499484

In [16]:
a4-12

array([[ -8,   0,  -1,  -9],
       [  2,   1,  -8, -10],
       [ -3,  -8,   1,  -4]])

In [18]:
a3/a4

array([[-0.5       , -0.08333333,  0.        ,  0.33333333],
       [ 0.14285714,  0.23076923,  1.        ,  2.5       ],
       [ 0.66666667,  1.75      ,  0.61538462,  1.125     ]])

In [19]:
a3*a4

array([[ -8, -12,   0,   3],
       [ 28,  39,  16,  10],
       [ 54,  28, 104,  72]])

In [20]:
a4

array([[ 4, 12, 11,  3],
       [14, 13,  4,  2],
       [ 9,  4, 13,  8]])

In [21]:
a4[:,0]

array([ 4, 14,  9])

In [30]:
a4[:,0].reshape(len(a4),1)

array([[ 4],
       [14],
       [ 9]])

In [3]:
s= np.array([1,2,3,4,5])

In [4]:
s.sum()

15

In [5]:
np.sum(s)

15

In [7]:
#二维数组索引
q = np.random.randint(2,10,(3,4))

In [8]:
q

array([[2, 3, 3, 3],
       [4, 9, 8, 8],
       [7, 7, 5, 8]])

In [12]:
q[0,0],q[0][1]

(2, 3)

In [15]:
#直接选行
q[1]

array([4, 9, 8, 8])

In [16]:
#选列
q[:,1]

array([3, 9, 7])

In [17]:
#选区，分块
#array([[2, 3, 3, 3],
#      [4, 9, 8, 8],
#     [7, 7, 5, 8]])
q[1:,1:3]

array([[9, 8],
       [7, 5]])

In [20]:
#切片：将选区赋给变量
split =q[:2,2:].copy()  #Ignore split（孤立切片）

In [19]:
split

array([[3, 3],
       [8, 8]])

In [23]:
#广播功能，就是批量赋值
split[:] = 5

In [24]:
split

array([[5, 5],
       [5, 5]])

In [25]:
q

array([[2, 3, 3, 3],
       [4, 9, 8, 8],
       [7, 7, 5, 8]])

In [26]:
split[1]=[6,8] #通过列表赋值

In [27]:
split

array([[5, 5],
       [6, 8]])

In [42]:
split[:,0] = 88,99  #通过元组赋值

In [41]:
split

array([[88,  5],
       [99,  8]])

In [ ]:
#可以通过元组，列表，嵌套列表，嵌套元组，或者一维、二维数组对切片或选区赋值

In [43]:
三维数组的索引与选区

hello


In [44]:
%who

a1	 np	 q	 s	 split	 


In [46]:
sw = np.random.randint(1,10,(2,3,4))
sw

array([[[8, 8, 1, 1],
        [8, 3, 6, 8],
        [9, 7, 4, 7]],

       [[8, 8, 2, 9],
        [4, 6, 9, 5],
        [9, 5, 8, 8]]])

In [48]:
#找出第一个6
sw[0,1,2]

6

In [51]:
#找出4,6,9,5行
sw[1,1]  #或sw[1,1,:]

array([4, 6, 9, 5])

In [56]:
#找出8,3,7,8,6,5列
sw[:,:,1].reshape((sw[:,:,1]).size,1)

array([[8],
       [3],
       [7],
       [8],
       [6],
       [5]])

In [65]:
#布尔数组
bl = np.random.randint(3,10,(3,4))
bl

array([[9, 4, 8, 8],
       [8, 3, 3, 7],
       [6, 9, 6, 4]])

In [66]:
bl==9  #判断操作

array([[ True, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [74]:
(bl>9)|(bl<4)|(bl==9)  #条件需要括号括起来   |或 &与 ~非

array([[ True, False, False, False],
       [False,  True,  True, False],
       [False,  True, False, False]])

In [76]:
~(bl==8)

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [79]:
#布尔数组帮助进行索引
sy = np.random.randint(2,10,(6,5))
sy

array([[3, 8, 8, 2, 2],
       [5, 4, 5, 9, 6],
       [4, 2, 8, 6, 3],
       [5, 6, 4, 5, 8],
       [4, 8, 4, 8, 7],
       [5, 2, 7, 8, 6]])

In [84]:
sy[:,0] = [0,1,1,0,0,1]
sy

array([[0, 8, 8, 2, 2],
       [1, 4, 5, 9, 6],
       [1, 2, 8, 6, 3],
       [0, 6, 4, 5, 8],
       [0, 8, 4, 8, 7],
       [1, 2, 7, 8, 6]])

In [85]:
sy[:,0] == 0

array([ True, False, False,  True,  True, False])

In [86]:
sy[sy[:,0]==0] #作为判断条件筛选数组

array([[0, 8, 8, 2, 2],
       [0, 6, 4, 5, 8],
       [0, 8, 4, 8, 7]])

In [87]:
gg = np.random.randint(1,10,(6,6))
gg

array([[3, 2, 8, 4, 1, 9],
       [5, 1, 4, 3, 8, 8],
       [4, 9, 9, 2, 1, 9],
       [5, 1, 8, 8, 5, 5],
       [2, 8, 2, 7, 3, 2],
       [7, 2, 9, 1, 1, 1]])

In [94]:
#花式索引一
gg[[1,2,-1]] #第一行，第二行，最后一行

array([[5, 1, 4, 3, 8, 8],
       [4, 9, 9, 2, 1, 9],
       [7, 2, 9, 1, 1, 1]])

In [95]:
#花式索引二
gg[:,[1,2,-1]]  #所有行的第一列，第二列，最后一列

array([[2, 8, 9],
       [1, 4, 8],
       [9, 9, 9],
       [1, 8, 5],
       [8, 2, 2],
       [2, 9, 1]])

In [110]:
#花式索引3=1*2
gg

array([[3, 2, 8, 4, 1, 9],
       [5, 1, 4, 3, 8, 8],
       [4, 9, 9, 2, 1, 9],
       [5, 1, 8, 8, 5, 5],
       [2, 8, 2, 7, 3, 2],
       [7, 2, 9, 1, 1, 1]])

In [111]:
gg[[0,1,2]][:,[1,2,3]]

array([[2, 8, 4],
       [1, 4, 3],
       [9, 9, 2]])

In [112]:
#花式索引4
gg[[0,1,2],[2,1,3]] #第0行的第2个元素，第1行的第1个元素...

array([8, 1, 2])

In [113]:
gg[np.ix_([0,1,2],[2,1,3])] #笛卡尔积（0,2）（0,1）（0,3）（1,2）（1,1）...

array([[8, 2, 4],
       [4, 1, 3],
       [9, 9, 2]])

In [114]:
#二维数组转置 ,一维数组转置后不变
gg

array([[3, 2, 8, 4, 1, 9],
       [5, 1, 4, 3, 8, 8],
       [4, 9, 9, 2, 1, 9],
       [5, 1, 8, 8, 5, 5],
       [2, 8, 2, 7, 3, 2],
       [7, 2, 9, 1, 1, 1]])

In [115]:
gg.T

array([[3, 5, 4, 5, 2, 7],
       [2, 1, 9, 1, 8, 2],
       [8, 4, 9, 8, 2, 9],
       [4, 3, 2, 8, 7, 1],
       [1, 8, 1, 5, 3, 1],
       [9, 8, 9, 5, 2, 1]])

In [118]:
#三维数组转置  三元组（0,1,2）
st= np.random.randint(1,30,(3,4,5))
st

array([[[16, 24,  9, 23, 24],
        [ 2, 16,  4, 21, 20],
        [14, 14, 18,  7, 11],
        [ 9, 26, 15,  2, 29]],

       [[24, 23, 10, 27,  4],
        [24,  8, 24,  5,  4],
        [20,  4, 22, 10, 23],
        [ 2, 20, 26, 14,  2]],

       [[19, 18,  7,  6, 13],
        [ 1, 29, 11,  7, 25],
        [ 5,  6, 21, 26,  4],
        [17,  5, 12, 14,  3]]])

In [119]:
st.shape

(3, 4, 5)

In [120]:
st.transpose(0,2,1) #相当于shape变成（3,5,4），将原来每个元素的索引值的维度调换位置

array([[[16,  2, 14,  9],
        [24, 16, 14, 26],
        [ 9,  4, 18, 15],
        [23, 21,  7,  2],
        [24, 20, 11, 29]],

       [[24, 24, 20,  2],
        [23,  8,  4, 20],
        [10, 24, 22, 26],
        [27,  5, 10, 14],
        [ 4,  4, 23,  2]],

       [[19,  1,  5, 17],
        [18, 29,  6,  5],
        [ 7, 11, 21, 12],
        [ 6,  7, 26, 14],
        [13, 25,  4,  3]]])

In [121]:
st

array([[[16, 24,  9, 23, 24],
        [ 2, 16,  4, 21, 20],
        [14, 14, 18,  7, 11],
        [ 9, 26, 15,  2, 29]],

       [[24, 23, 10, 27,  4],
        [24,  8, 24,  5,  4],
        [20,  4, 22, 10, 23],
        [ 2, 20, 26, 14,  2]],

       [[19, 18,  7,  6, 13],
        [ 1, 29, 11,  7, 25],
        [ 5,  6, 21, 26,  4],
        [17,  5, 12, 14,  3]]])

In [125]:
st.transpose(1,0,2) #相当于shape变成（4,3,5）

array([[[16, 24,  9, 23, 24],
        [24, 23, 10, 27,  4],
        [19, 18,  7,  6, 13]],

       [[ 2, 16,  4, 21, 20],
        [24,  8, 24,  5,  4],
        [ 1, 29, 11,  7, 25]],

       [[14, 14, 18,  7, 11],
        [20,  4, 22, 10, 23],
        [ 5,  6, 21, 26,  4]],

       [[ 9, 26, 15,  2, 29],
        [ 2, 20, 26, 14,  2],
        [17,  5, 12, 14,  3]]])

In [124]:
#全转置1
st.transpose(2,1,0)

array([[[16, 24, 19],
        [ 2, 24,  1],
        [14, 20,  5],
        [ 9,  2, 17]],

       [[24, 23, 18],
        [16,  8, 29],
        [14,  4,  6],
        [26, 20,  5]],

       [[ 9, 10,  7],
        [ 4, 24, 11],
        [18, 22, 21],
        [15, 26, 12]],

       [[23, 27,  6],
        [21,  5,  7],
        [ 7, 10, 26],
        [ 2, 14, 14]],

       [[24,  4, 13],
        [20,  4, 25],
        [11, 23,  4],
        [29,  2,  3]]])

In [126]:
#全转置2
st.T

array([[[16, 24, 19],
        [ 2, 24,  1],
        [14, 20,  5],
        [ 9,  2, 17]],

       [[24, 23, 18],
        [16,  8, 29],
        [14,  4,  6],
        [26, 20,  5]],

       [[ 9, 10,  7],
        [ 4, 24, 11],
        [18, 22, 21],
        [15, 26, 12]],

       [[23, 27,  6],
        [21,  5,  7],
        [ 7, 10, 26],
        [ 2, 14, 14]],

       [[24,  4, 13],
        [20,  4, 25],
        [11, 23,  4],
        [29,  2,  3]]])

In [127]:
st.swapaxes(0,1) #接受一对维度的更换位置，相当于st.transpose(1,0,2)

array([[[16, 24,  9, 23, 24],
        [24, 23, 10, 27,  4],
        [19, 18,  7,  6, 13]],

       [[ 2, 16,  4, 21, 20],
        [24,  8, 24,  5,  4],
        [ 1, 29, 11,  7, 25]],

       [[14, 14, 18,  7, 11],
        [20,  4, 22, 10, 23],
        [ 5,  6, 21, 26,  4]],

       [[ 9, 26, 15,  2, 29],
        [ 2, 20, 26, 14,  2],
        [17,  5, 12, 14,  3]]])

In [128]:
st.transpose(1,0,2)

array([[[16, 24,  9, 23, 24],
        [24, 23, 10, 27,  4],
        [19, 18,  7,  6, 13]],

       [[ 2, 16,  4, 21, 20],
        [24,  8, 24,  5,  4],
        [ 1, 29, 11,  7, 25]],

       [[14, 14, 18,  7, 11],
        [20,  4, 22, 10, 23],
        [ 5,  6, 21, 26,  4]],

       [[ 9, 26, 15,  2, 29],
        [ 2, 20, 26, 14,  2],
        [17,  5, 12, 14,  3]]])